<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputPath>C:\Users\megag\Documents\tShock61\ServerPlugins</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="OTAPI">
            <HintPath>C:\Users\megag\Documents\tShock61\bin\OTAPI.dll</HintPath>
        </Reference>
        <Reference Include="TerrariaServer">
            <HintPath>C:\Users\megag\Documents\tShock61\bin\TerrariaServer.dll</HintPath>
        </Reference>
        <Reference Include="TShockAPI">
            <HintPath>C:\Users\megag\Documents\tShock61\ServerPlugins\TShockAPI.dll</HintPath>
        </Reference>
    </ItemGroup>
    
    
</Project>
